# name: CI

# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches: [main]

# jobs:
#   test:
#     runs-on: ubuntu-22.04
#     steps:
#       - uses: actions/checkout@v4
#       - uses: actions/setup-node@v4
#       - name: Install NPM dependencies
#         run: npm ci
#       - name: Build Next.js app
#         run: npm run build
#       - name: Install Playwright Browsers
#         run: npx playwright install --with-deps
#       - name: Run Playwright tests
#         run: npx playwright test
#       - uses: actions/upload-artifact@v4
#         if: always()
#         with:
#           name: playwright-report
#           path: playwright-report/
#           retention-days: 2
